import Head from 'next/head';

import data from '@/lib/data';
import ListingCardItem from '@/components/listing-card-item';

export default function Home({ listingData }) {
  return (
    <>
      <Head>
        <title>99.co Frontend Test</title>
        <meta name="description" content="Generated by create next app for 99.co" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex justify-center items-center p-3">
          <ListingCardItem listingData={listingData} />
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  return {
    props: {
      listingData: data,
    },
  };
}
